# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
No console.log('Outside the loop'); will not run. This is because i will never be greater than 3.  The loop will stop before  i = 3 so tht console.log('Outside the loop'); will not exacute    

# Teacher Feedback
